extends: stylelint-config-standard
rules:
  alpha-value-notation: [number, { severity: warning }]
  block-closing-brace-newline-after: [always, { severity: warning }]
  color-function-notation: [modern, { severity: warning }]
  color-hex-length: [short, { severity: warning }]
  comment-empty-line-before: [always, { severity: warning }]
  custom-property-pattern: [null]
  declaration-block-no-duplicate-properties: [true, { severity: warning }]
  declaration-block-semicolon-newline-after: [always-multi-line, { severity: warning }]
  declaration-block-single-line-max-declarations: [8, { severity: warning }]
  declaration-block-trailing-semicolon: [always, { severity: warning }]
  declaration-colon-space-after: [always, { severity: warning }]
  font-family-name-quotes: [always-unless-keyword, { severity: warning }]
  indentation: [2, { severity: warning }]
  length-zero-no-unit: [true, { severity: warning }]
  max-empty-lines: [2, { severity: warning }]
  max-line-length: [100, { severity: warning }]
  no-descending-specificity: [true, { severity: warning }]
  no-duplicate-selectors: [true, { severity: warning }]
  no-eol-whitespace: [true, { severity: warning }]
  number-no-trailing-zeros: [true, { severity: warning }]
  property-no-vendor-prefix: [true, { severity: warning }]
  rule-empty-line-before: [null]
  selector-attribute-quotes: [never, { severity: warning }]
  selector-class-pattern: [null]
  selector-combinator-space-after: [always, { severity: warning }]
  selector-combinator-space-before: [always, { severity: warning }]
  selector-id-pattern: [null]
  selector-pseudo-element-colon-notation: [single, { severity: warning }]
  shorthand-property-no-redundant-values: [true, { severity: warning }]
  string-quotes: [double, { severity: warning }]
  value-keyword-case: [lower, { severity: warning }]
