/* eslint-disable @typescript-eslint/naming-convention */
import * as Circle from "./circle_schema_generated";

export enum BuiltinOptionsType {
  NONE = 0,
  CONV2DOPTIONS = 1,
  DEPTHWISECONV2DOPTIONS = 2,
  CONCATEMBEDDINGSOPTIONS = 3,
  LSHPROJECTIONOPTIONS = 4,
  POOL2DOPTIONS = 5,
  SVDFOPTIONS = 6,
  RNNOPTIONS = 7,
  FULLYCONNECTEDOPTIONS = 8,
  SOFTMAXOPTIONS = 9,
  CONCATENATIONOPTIONS = 10,
  ADDOPTIONS = 11,
  L2NORMOPTIONS = 12,
  LOCALRESPONSENORMALIZATIONOPTIONS = 13,
  LSTMOPTIONS = 14,
  RESIZEBILINEAROPTIONS = 15,
  CALLOPTIONS = 16,
  RESHAPEOPTIONS = 17,
  SKIPGRAMOPTIONS = 18,
  SPACETODEPTHOPTIONS = 19,
  EMBEDDINGLOOKUPSPARSEOPTIONS = 20,
  MULOPTIONS = 21,
  PADOPTIONS = 22,
  GATHEROPTIONS = 23,
  BATCHTOSPACENDOPTIONS = 24,
  SPACETOBATCHNDOPTIONS = 25,
  TRANSPOSEOPTIONS = 26,
  REDUCEROPTIONS = 27,
  SUBOPTIONS = 28,
  DIVOPTIONS = 29,
  SQUEEZEOPTIONS = 30,
  SEQUENCERNNOPTIONS = 31,
  STRIDEDSLICEOPTIONS = 32,
  EXPOPTIONS = 33,
  TOPKV2OPTIONS = 34,
  SPLITOPTIONS = 35,
  LOGSOFTMAXOPTIONS = 36,
  CASTOPTIONS = 37,
  DEQUANTIZEOPTIONS = 38,
  MAXIMUMMINIMUMOPTIONS = 39,
  ARGMAXOPTIONS = 40,
  LESSOPTIONS = 41,
  NEGOPTIONS = 42,
  PADV2OPTIONS = 43,
  GREATEROPTIONS = 44,
  GREATEREQUALOPTIONS = 45,
  LESSEQUALOPTIONS = 46,
  SELECTOPTIONS = 47,
  SLICEOPTIONS = 48,
  TRANSPOSECONVOPTIONS = 49,
  SPARSETODENSEOPTIONS = 50,
  TILEOPTIONS = 51,
  EXPANDDIMSOPTIONS = 52,
  EQUALOPTIONS = 53,
  NOTEQUALOPTIONS = 54,
  SHAPEOPTIONS = 55,
  POWOPTIONS = 56,
  ARGMINOPTIONS = 57,
  FAKEQUANTOPTIONS = 58,
  PACKOPTIONS = 59,
  LOGICALOROPTIONS = 60,
  ONEHOTOPTIONS = 61,
  LOGICALANDOPTIONS = 62,
  LOGICALNOTOPTIONS = 63,
  UNPACKOPTIONS = 64,
  FLOORDIVOPTIONS = 65,
  SQUAREOPTIONS = 66,
  ZEROSLIKEOPTIONS = 67,
  FILLOPTIONS = 68,
  BIDIRECTIONALSEQUENCELSTMOPTIONS = 69,
  BIDIRECTIONALSEQUENCERNNOPTIONS = 70,
  UNIDIRECTIONALSEQUENCELSTMOPTIONS = 71,
  FLOORMODOPTIONS = 72,
  RANGEOPTIONS = 73,
  RESIZENEARESTNEIGHBOROPTIONS = 74,
  LEAKYRELUOPTIONS = 75,
  SQUAREDDIFFERENCEOPTIONS = 76,
  MIRRORPADOPTIONS = 77,
  ABSOPTIONS = 78,
  SPLITVOPTIONS = 79,
  UNIQUEOPTIONS = 80,
  REVERSEV2OPTIONS = 81,
  ADDNOPTIONS = 82,
  GATHERNDOPTIONS = 83,
  COSOPTIONS = 84,
  WHEREOPTIONS = 85,
  RANKOPTIONS = 86,
  REVERSESEQUENCEOPTIONS = 87,
  MATRIXDIAGOPTIONS = 88,
  QUANTIZEOPTIONS = 89,
  MATRIXSETDIAGOPTIONS = 90,
  HARDSWISHOPTIONS = 91,
  IFOPTIONS = 92,
  WHILEOPTIONS = 93,
  DEPTHTOSPACEOPTIONS = 94,
  NONMAXSUPPRESSIONV4OPTIONS = 95,
  NONMAXSUPPRESSIONV5OPTIONS = 96,
  SCATTERNDOPTIONS = 97,
  SELECTV2OPTIONS = 98,
  DENSIFYOPTIONS = 99,
  SEGMENTSUMOPTIONS = 100,
  BATCHMATMULOPTIONS = 101,
  CUMSUMOPTIONS = 102,
  CALLONCEOPTIONS = 103,
  BROADCASTTOOPTIONS = 104,
  RFFT2DOPTIONS = 105,
  CONV3DOPTIONS = 106,
  HASHTABLEOPTIONS = 107,
  HASHTABLEFINDOPTIONS = 108,
  HASHTABLEIMPORTOPTIONS = 109,
  HASHTABLESIZEOPTIONS = 110,
  VARHANDLEOPTIONS = 111,
  READVARIABLEOPTIONS = 112,
  ASSIGNVARIABLEOPTIONS = 113,
  RANDOMOPTIONS = 114,
  BCQGATHEROPTIONS = 252,
  BCQFULLYCONNECTEDOPTIONS = 253,
  INSTANCENORMOPTIONS = 254,
}

export const CircleType: any = {
  TensorType: Circle.TensorType,
  DimensionType: Circle.DimensionType,
  Padding: Circle.Padding,
  ActivationFunctionType: Circle.ActivationFunctionType,
  LSHProjectionType: Circle.LSHProjectionType,
  FullyConnectedOptionsWeightsFormat: Circle.FullyConnectedOptionsWeightsFormat,
  LSTMKernelType: Circle.LSTMKernelType,
  CombinerType: Circle.CombinerType,
  MirrorPadMode: Circle.MirrorPadMode,
  CustomOptionsFormat: Circle.CustomOptionsFormat,
  DataFormat: Circle.DataFormat,
};

export const NormalType: any = {
  int: Number,
  int32: Number,
  string: String,
  byte: Number,
  ubyte: Number,
  uint: Number,
  int64: Number,
  int16: Number,
  uint16: Number,
  uint32: Number,
  uint64: Number,
  "int32[]": Int32Array,
  "int16[]": Int16Array,
  "uint32[]": Uint32Array,
  "uint16[]": Uint16Array,
  "float32[]": Float32Array,
  "float64[]": Float64Array,
};

export const FindAttribute: any = {
  CONV2DOPTIONS: Circle.Conv2DOptionsT,
  DEPTHWISECONV2DOPTIONS: Circle.DensifyOptionsT,
  CONCATEMBEDDINGSOPTIONS: Circle.ConcatEmbeddingsOptionsT,
  LSHPROJECTIONOPTIONS: Circle.LSHProjectionOptionsT,
  POOL2DOPTIONS: Circle.Pool2DOptionsT,
  SVDFOPTIONS: Circle.SVDFOptionsT,
  RNNOPTIONS: Circle.RNNOptionsT,
  FULLYCONNECTEDOATIONOPTIONS: Circle.FullyConnectedOptionsT,
  SOFTMAXOPTIONS: Circle.SoftmaxOptionsT,
  CONCATENATIONOPTIONS: Circle.ConcatenationOptionsT,
  ADDOPTIONS: Circle.AddOptionsT,
  L2NORMOPTIONS: Circle.L2NormOptionsT,
  LOCALRESPONSENORMALIZATIONOPTIONS: Circle.LocalResponseNormalizationOptionsT,
  LSTMOPTIONS: Circle.LSTMOptionsT,
  RESIZEBILINEAROPTIONS: Circle.ResizeBilinearOptionsT,
  CALLOPTIONS: Circle.CallOptionsT,
  RESHAPEOPTIONS: Circle.ReshapeOptionsT,
  SKIPGRAMOPTIONS: Circle.SkipGramOptionsT,
  SPACETODEPTHOPTIONS: Circle.SpaceToDepthOptionsT,
  EMBEDDINGLOOKUPSPARSEOPTIONS: Circle.EmbeddingLookupSparseOptionsT,
  MULOPTIONS: Circle.MulOptionsT,
  PADOPTIONS: Circle.PadOptionsT,
  GATHEROPTIONS: Circle.GatherOptionsT,
  BATCHTOSPACENDOPTIONS: Circle.BatchToSpaceNDOptionsT,
  SPACETOBATCHNDOPTIONS: Circle.SpaceToBatchNDOptionsT,
  TRANSPOSEOPTIONS: Circle.TransposeOptionsT,
  REDUCEROPTIONS: Circle.ReducerOptionsT,
  SUBOPTIONS: Circle.SubOptionsT,
  DIVOPTIONS: Circle.DivOptionsT,
  SQUEEZEOPTIONS: Circle.SqueezeOptionsT,
  SEQUENCERNNOPTIONS: Circle.SequenceRNNOptionsT,
  STRIDEDSLICEOPTIONS: Circle.StridedSliceOptionsT,
  EXPOPTIONS: Circle.ExpOptionsT,
  TOPKV2OPTIONS: Circle.TopKV2OptionsT,
  SPLITOPTIONS: Circle.SplitOptionsT,
  LOGSOFTMAXOPTIONS: Circle.LogSoftmaxOptionsT,
  CASTOPTIONS: Circle.CastOptionsT,
  DEQUANTIZEOPTIONS: Circle.DequantizeOptionsT,
  MAXIMUMMINIMUMOPTIONS: Circle.MaximumMinimumOptionsT,
  ARGMAXOPTIONS: Circle.ArgMaxOptionsT,
  LESSOPTIONS: Circle.LessOptionsT,
  NEGOPTIONS: Circle.NegOptionsT,
  PADV2OPTIONS: Circle.PadV2OptionsT,
  GREATEROPTIONS: Circle.GreaterOptionsT,
  GREATEREQUALOPTIONS: Circle.GreaterEqualOptionsT,
  LESSEQUALOPTIONS: Circle.LessEqualOptionsT,
  SELECTOPTIONS: Circle.SelectOptionsT,
  SLICEOPTIONS: Circle.SliceOptionsT,
  TRANSPOSECONVOPTIONS: Circle.TransposeConvOptionsT,
  SPARSETODENSEOPTIONS: Circle.SparseToDenseOptionsT,
  TILEOPTIONS: Circle.TileOptionsT,
  EXPANDDIMSOPTIONS: Circle.ExpandDimsOptionsT,
  EQUALOPTIONS: Circle.EqualOptionsT,
  NOTEQUALOPTIONS: Circle.NotEqualOptionsT,
  SHAPEOPTIONS: Circle.ShapeOptionsT,
  POWOPTIONS: Circle.PowOptionsT,
  ARGMINOPTIONS: Circle.ArgMinOptionsT,
  FAKEQUANTOPTIONS: Circle.FakeQuantOptionsT,
  PACKOPTIONS: Circle.PackOptionsT,
  LOGICALOROPTIONS: Circle.LogicalOrOptionsT,
  ONEHOTOPTIONS: Circle.OneHotOptionsT,
  LOGICALANDOPTIONS: Circle.LogicalAndOptionsT,
  LOGICALNOTOPTIONS: Circle.LogicalNotOptionsT,
  UNPACKOPTIONS: Circle.UnpackOptionsT,
  FLOORDIVOPTIONS: Circle.FloorDivOptionsT,
  SQUAREOPTIONS: Circle.SquareOptionsT,
  ZEROSLIKEOPTIONS: Circle.ZerosLikeOptionsT,
  FILLOPTIONS: Circle.FillOptionsT,
  BIDIRECTIONALSEQUENCELSTMOPTIONS: Circle.BidirectionalSequenceLSTMOptionsT,
  BIDIRECTIONALSEQUENCERNNOPTIONS: Circle.BidirectionalSequenceRNNOptionsT,
  UNIDIRECTIONALSEQUENCELSTMOPTIONS: Circle.UnidirectionalSequenceLSTMOptionsT,
  FLOORMODOPTIONS: Circle.FloorModOptionsT,
  RANGEOPTIONS: Circle.RangeOptionsT,
  RESIZENEARESTNEIGHBOROPTIONS: Circle.ResizeNearestNeighborOptionsT,
  LEAKYRELUOPTIONS: Circle.LeakyReluOptionsT,
  SQUAREDDIFFERENCEOPTIONS: Circle.SquaredDifferenceOptionsT,
  MIRRORPADOPTIONS: Circle.MirrorPadOptionsT,
  ABSOPTIONS: Circle.AbsOptionsT,
  SPLITVOPTIONS: Circle.SplitVOptionsT,
  UNIQUEOPTIONS: Circle.UniqueOptionsT,
  REVERSEV2OPTIONS: Circle.ReverseV2OptionsT,
  ADDNOPTIONS: Circle.AddNOptionsT,
  GATHERNDOPTIONS: Circle.GatherNdOptionsT,
  COSOPTIONS: Circle.CosOptionsT,
  WHEREOPTIONS: Circle.WhereOptionsT,
  RANKOPTIONS: Circle.RankOptionsT,
  REVERSESEQUENCEOPTIONS: Circle.ReverseSequenceOptionsT,
  MATRIXDIAGOPTIONS: Circle.MatrixDiagOptionsT,
  QUANTIZEOPTIONS: Circle.QuantizeOptionsT,
  MATRIXSETDIAGOPTIONS: Circle.MatrixSetDiagOptionsT,
  HARDSWISHOPTIONS: Circle.HardSwishOptionsT,
  IFOPTIONS: Circle.IfOptionsT,
  WHILEOPTIONS: Circle.WhileOptionsT,
  DEPTHTOSPACEOPTIONS: Circle.DepthToSpaceOptionsT,
  NONMAXSUPPRESSIONV4OPTIONS: Circle.NonMaxSuppressionV4OptionsT,
  NONMAXSUPPRESSIONV5OPTIONS: Circle.NonMaxSuppressionV5OptionsT,
  SCATTERNDOPTIONS: Circle.ScatterNdOptionsT,
  SELECTV2OPTIONS: Circle.SelectV2OptionsT,
  DENSIFYOPTIONS: Circle.DensifyOptionsT,
  SEGMENTSUMOPTIONS: Circle.SegmentSumOptionsT,
  BATCHMATMULOPTIONS: Circle.BatchMatMulOptionsT,
  CUMSUMOPTIONS: Circle.CumsumOptionsT,
  CALLONCEOPTIONS: Circle.CallOnceOptionsT,
  BROADCASTTOOPTIONS: Circle.BroadcastToOptionsT,
  RFFT2DOPTIONS: Circle.Rfft2dOptionsT,
  CONV3DOPTIONS: Circle.Conv3DOptionsT,
  HASHTABLEOPTIONS: Circle.HashtableOptionsT,
  HASHTABLEFINDOPTIONS: Circle.HashtableFindOptionsT,
  HASHTABLEIMPORTOPTIONS: Circle.HashtableImportOptionsT,
  HASHTABLESIZEOPTIONS: Circle.HashtableSizeOptionsT,
  VARHANDLEOPTIONS: Circle.VarHandleOptionsT,
  READVARIABLEOPTIONS: Circle.ReadVariableOptionsT,
  ASSIGNVARIABLEOPTIONS: Circle.AssignVariableOptionsT,
  RANDOMOPTIONS: Circle.RandomOptionsT,
  BCQGATHEROPTIONS: Circle.BCQGatherOptionsT,
  BCQFULLYCONNECTEDOPTIONS: Circle.BCQFullyConnectedOptionsT,
  INSTANCENORMOPTIONS: Circle.InstanceNormOptionsT,
};

export const NumberToBuiltinOptions = {
  0: null,
  1: Circle.Conv2DOptionsT,
  2: Circle.DepthwiseConv2DOptionsT,
  3: Circle.ConcatEmbeddingsOptionsT,
  4: Circle.LSHProjectionOptionsT,
  5: Circle.Pool2DOptionsT,
  6: Circle.SVDFOptionsT,
  7: Circle.RNNOptionsT,
  8: Circle.FullyConnectedOptionsT,
  9: Circle.SoftmaxOptionsT,
  10: Circle.ConcatenationOptionsT,
  11: Circle.AddOptionsT,
  12: Circle.L2NormOptionsT,
  13: Circle.LocalResponseNormalizationOptionsT,
  14: Circle.LSTMOptionsT,
  15: Circle.ResizeBilinearOptionsT,
  16: Circle.CallOptionsT,
  17: Circle.ReshapeOptionsT,
  18: Circle.SkipGramOptionsT,
  19: Circle.SpaceToDepthOptionsT,
  20: Circle.EmbeddingLookupSparseOptionsT,
  21: Circle.MulOptionsT,
  22: Circle.PadOptionsT,
  23: Circle.GatherOptionsT,
  24: Circle.BatchToSpaceNDOptionsT,
  25: Circle.SpaceToBatchNDOptionsT,
  26: Circle.TransposeOptionsT,
  27: Circle.ReducerOptionsT,
  28: Circle.SubOptionsT,
  29: Circle.DivOptionsT,
  30: Circle.SqueezeOptionsT,
  31: Circle.SequenceRNNOptionsT,
  32: Circle.StridedSliceOptionsT,
  33: Circle.ExpOptionsT,
  34: Circle.TopKV2OptionsT,
  35: Circle.SplitOptionsT,
  36: Circle.LogSoftmaxOptionsT,
  37: Circle.CastOptionsT,
  38: Circle.DequantizeOptionsT,
  39: Circle.MaximumMinimumOptionsT,
  40: Circle.ArgMaxOptionsT,
  41: Circle.LessOptionsT,
  42: Circle.NegOptionsT,
  43: Circle.PadV2OptionsT,
  44: Circle.GreaterOptionsT,
  45: Circle.GreaterEqualOptionsT,
  46: Circle.LessEqualOptionsT,
  47: Circle.SelectOptionsT,
  48: Circle.SliceOptionsT,
  49: Circle.TransposeConvOptionsT,
  50: Circle.SparseToDenseOptionsT,
  51: Circle.TileOptionsT,
  52: Circle.ExpandDimsOptionsT,
  53: Circle.EqualOptionsT,
  54: Circle.NotEqualOptionsT,
  55: Circle.ShapeOptionsT,
  56: Circle.PowOptionsT,
  57: Circle.ArgMinOptionsT,
  58: Circle.FakeQuantOptionsT,
  59: Circle.PackOptionsT,
  60: Circle.LogicalOrOptionsT,
  61: Circle.OneHotOptionsT,
  62: Circle.LogicalAndOptionsT,
  63: Circle.LogicalNotOptionsT,
  64: Circle.UnpackOptionsT,
  65: Circle.FloorDivOptionsT,
  66: Circle.SquareOptionsT,
  67: Circle.ZerosLikeOptionsT,
  68: Circle.FillOptionsT,
  69: Circle.BidirectionalSequenceLSTMOptionsT,
  70: Circle.BidirectionalSequenceRNNOptionsT,
  71: Circle.UnidirectionalSequenceLSTMOptionsT,
  72: Circle.FloorModOptionsT,
  73: Circle.RangeOptionsT,
  74: Circle.ResizeNearestNeighborOptionsT,
  75: Circle.LeakyReluOptionsT,
  76: Circle.SquaredDifferenceOptionsT,
  77: Circle.MirrorPadOptionsT,
  78: Circle.AbsOptionsT,
  79: Circle.SplitVOptionsT,
  80: Circle.UniqueOptionsT,
  81: Circle.ReverseV2OptionsT,
  82: Circle.AddNOptionsT,
  83: Circle.GatherNdOptionsT,
  84: Circle.CosOptionsT,
  85: Circle.WhereOptionsT,
  86: Circle.RankOptionsT,
  87: Circle.ReverseSequenceOptionsT,
  88: Circle.MatrixDiagOptionsT,
  89: Circle.QuantizeOptionsT,
  90: Circle.MatrixSetDiagOptionsT,
  91: Circle.HardSwishOptionsT,
  92: Circle.IfOptionsT,
  93: Circle.WhileOptionsT,
  94: Circle.DepthToSpaceOptionsT,
  95: Circle.NonMaxSuppressionV4OptionsT,
  96: Circle.NonMaxSuppressionV5OptionsT,
  97: Circle.ScatterNdOptionsT,
  98: Circle.SelectV2OptionsT,
  99: Circle.DensifyOptionsT,
  100: Circle.SegmentSumOptionsT,
  101: Circle.BatchMatMulOptionsT,
  102: Circle.CumsumOptionsT,
  103: Circle.CallOnceOptionsT,
  104: Circle.BroadcastToOptionsT,
  105: Circle.Rfft2dOptionsT,
  106: Circle.Conv3DOptionsT,
  107: Circle.HashtableOptionsT,
  108: Circle.HashtableFindOptionsT,
  109: Circle.HashtableImportOptionsT,
  110: Circle.HashtableSizeOptionsT,
  111: Circle.VarHandleOptionsT,
  112: Circle.ReadVariableOptionsT,
  113: Circle.AssignVariableOptionsT,
  114: Circle.RandomOptionsT,
  252: Circle.BCQGatherOptionsT,
  253: Circle.BCQFullyConnectedOptionsT,
  254: Circle.InstanceNormOptionsT,
};

export const SparseVector = {
  0: null,
  1: Circle.Int32VectorT,
  2: Circle.Uint16VectorT,
  3: Circle.Uint8VectorT,
};
