// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class BroadcastToOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BroadcastToOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBroadcastToOptions(bb:flatbuffers.ByteBuffer, obj?:BroadcastToOptions):BroadcastToOptions {
  return (obj || new BroadcastToOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBroadcastToOptions(bb:flatbuffers.ByteBuffer, obj?:BroadcastToOptions):BroadcastToOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BroadcastToOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startBroadcastToOptions(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endBroadcastToOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBroadcastToOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  BroadcastToOptions.startBroadcastToOptions(builder);
  return BroadcastToOptions.endBroadcastToOptions(builder);
}

unpack(): BroadcastToOptionsT {
  return new BroadcastToOptionsT();
}


unpackTo(_o: BroadcastToOptionsT): void {}
}

export class BroadcastToOptionsT {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return BroadcastToOptions.createBroadcastToOptions(builder);
}
}
