// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class ResizeNearestNeighborOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ResizeNearestNeighborOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsResizeNearestNeighborOptions(bb:flatbuffers.ByteBuffer, obj?:ResizeNearestNeighborOptions):ResizeNearestNeighborOptions {
  return (obj || new ResizeNearestNeighborOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsResizeNearestNeighborOptions(bb:flatbuffers.ByteBuffer, obj?:ResizeNearestNeighborOptions):ResizeNearestNeighborOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ResizeNearestNeighborOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

alignCorners():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

halfPixelCenters():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startResizeNearestNeighborOptions(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addAlignCorners(builder:flatbuffers.Builder, alignCorners:boolean) {
  builder.addFieldInt8(0, +alignCorners, +false);
}

static addHalfPixelCenters(builder:flatbuffers.Builder, halfPixelCenters:boolean) {
  builder.addFieldInt8(1, +halfPixelCenters, +false);
}

static endResizeNearestNeighborOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createResizeNearestNeighborOptions(builder:flatbuffers.Builder, alignCorners:boolean, halfPixelCenters:boolean):flatbuffers.Offset {
  ResizeNearestNeighborOptions.startResizeNearestNeighborOptions(builder);
  ResizeNearestNeighborOptions.addAlignCorners(builder, alignCorners);
  ResizeNearestNeighborOptions.addHalfPixelCenters(builder, halfPixelCenters);
  return ResizeNearestNeighborOptions.endResizeNearestNeighborOptions(builder);
}

unpack(): ResizeNearestNeighborOptionsT {
  return new ResizeNearestNeighborOptionsT(
    this.alignCorners(),
    this.halfPixelCenters()
  );
}


unpackTo(_o: ResizeNearestNeighborOptionsT): void {
  _o.alignCorners = this.alignCorners();
  _o.halfPixelCenters = this.halfPixelCenters();
}
}

export class ResizeNearestNeighborOptionsT {
constructor(
  public alignCorners: boolean = false,
  public halfPixelCenters: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ResizeNearestNeighborOptions.createResizeNearestNeighborOptions(builder,
    this.alignCorners,
    this.halfPixelCenters
  );
}
}
