/*
 * Copyright (c) 2021 Samsung Electronics Co., Ltd. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import {TensorType} from '../circle/tensor-type';


export class ArgMinOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): ArgMinOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsArgMinOptions(bb: flatbuffers.ByteBuffer, obj?: ArgMinOptions): ArgMinOptions {
    return (obj || new ArgMinOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsArgMinOptions(bb: flatbuffers.ByteBuffer, obj?: ArgMinOptions):
      ArgMinOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new ArgMinOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  outputType(): TensorType {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.readInt8(this.bb_pos + offset) : TensorType.FLOAT32;
  }

  static startArgMinOptions(builder: flatbuffers.Builder) {
    builder.startObject(1);
  }

  static addOutputType(builder: flatbuffers.Builder, outputType: TensorType) {
    builder.addFieldInt8(0, outputType, TensorType.FLOAT32);
  }

  static endArgMinOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createArgMinOptions(builder: flatbuffers.Builder, outputType: TensorType):
      flatbuffers.Offset {
    ArgMinOptions.startArgMinOptions(builder);
    ArgMinOptions.addOutputType(builder, outputType);
    return ArgMinOptions.endArgMinOptions(builder);
  }
}
