// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import {ActivationFunctionType} from '../circle/activation-function-type';


export class BCQFullyConnectedOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): BCQFullyConnectedOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsBCQFullyConnectedOptions(
      bb: flatbuffers.ByteBuffer, obj?: BCQFullyConnectedOptions): BCQFullyConnectedOptions {
    return (obj || new BCQFullyConnectedOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsBCQFullyConnectedOptions(
      bb: flatbuffers.ByteBuffer, obj?: BCQFullyConnectedOptions): BCQFullyConnectedOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new BCQFullyConnectedOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  weightsHiddenSize(): number {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
  }

  fusedActivationFunction(): ActivationFunctionType {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.readInt8(this.bb_pos + offset) : ActivationFunctionType.NONE;
  }

  static startBCQFullyConnectedOptions(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addWeightsHiddenSize(builder: flatbuffers.Builder, weightsHiddenSize: number) {
    builder.addFieldInt32(0, weightsHiddenSize, 0);
  }

  static addFusedActivationFunction(
      builder: flatbuffers.Builder, fusedActivationFunction: ActivationFunctionType) {
    builder.addFieldInt8(1, fusedActivationFunction, ActivationFunctionType.NONE);
  }

  static endBCQFullyConnectedOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createBCQFullyConnectedOptions(
      builder: flatbuffers.Builder, weightsHiddenSize: number,
      fusedActivationFunction: ActivationFunctionType): flatbuffers.Offset {
    BCQFullyConnectedOptions.startBCQFullyConnectedOptions(builder);
    BCQFullyConnectedOptions.addWeightsHiddenSize(builder, weightsHiddenSize);
    BCQFullyConnectedOptions.addFusedActivationFunction(builder, fusedActivationFunction);
    return BCQFullyConnectedOptions.endBCQFullyConnectedOptions(builder);
  }
}
