/*
 * Copyright (c) 2021 Samsung Electronics Co., Ltd. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import {ActivationFunctionType} from '../circle/activation-function-type';


export class ConcatenationOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): ConcatenationOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsConcatenationOptions(bb: flatbuffers.ByteBuffer, obj?: ConcatenationOptions):
      ConcatenationOptions {
    return (obj || new ConcatenationOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsConcatenationOptions(
      bb: flatbuffers.ByteBuffer, obj?: ConcatenationOptions): ConcatenationOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new ConcatenationOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  axis(): number {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
  }

  fusedActivationFunction(): ActivationFunctionType {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.readInt8(this.bb_pos + offset) : ActivationFunctionType.NONE;
  }

  static startConcatenationOptions(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addAxis(builder: flatbuffers.Builder, axis: number) {
    builder.addFieldInt32(0, axis, 0);
  }

  static addFusedActivationFunction(
      builder: flatbuffers.Builder, fusedActivationFunction: ActivationFunctionType) {
    builder.addFieldInt8(1, fusedActivationFunction, ActivationFunctionType.NONE);
  }

  static endConcatenationOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createConcatenationOptions(
      builder: flatbuffers.Builder, axis: number,
      fusedActivationFunction: ActivationFunctionType): flatbuffers.Offset {
    ConcatenationOptions.startConcatenationOptions(builder);
    ConcatenationOptions.addAxis(builder, axis);
    ConcatenationOptions.addFusedActivationFunction(builder, fusedActivationFunction);
    return ConcatenationOptions.endConcatenationOptions(builder);
  }
}
