// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class ExpOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): ExpOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsExpOptions(bb: flatbuffers.ByteBuffer, obj?: ExpOptions): ExpOptions {
    return (obj || new ExpOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsExpOptions(bb: flatbuffers.ByteBuffer, obj?: ExpOptions): ExpOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new ExpOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static startExpOptions(builder: flatbuffers.Builder) {
    builder.startObject(0);
  }

  static endExpOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createExpOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    ExpOptions.startExpOptions(builder);
    return ExpOptions.endExpOptions(builder);
  }
}
