// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class FloorModOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): FloorModOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsFloorModOptions(bb: flatbuffers.ByteBuffer, obj?: FloorModOptions):
      FloorModOptions {
    return (obj || new FloorModOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsFloorModOptions(bb: flatbuffers.ByteBuffer, obj?: FloorModOptions):
      FloorModOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new FloorModOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static startFloorModOptions(builder: flatbuffers.Builder) {
    builder.startObject(0);
  }

  static endFloorModOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createFloorModOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    FloorModOptions.startFloorModOptions(builder);
    return FloorModOptions.endFloorModOptions(builder);
  }
}
