/*
 * Copyright (c) 2021 Samsung Electronics Co., Ltd. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class GreaterEqualOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): GreaterEqualOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsGreaterEqualOptions(bb: flatbuffers.ByteBuffer, obj?: GreaterEqualOptions):
      GreaterEqualOptions {
    return (obj || new GreaterEqualOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsGreaterEqualOptions(
      bb: flatbuffers.ByteBuffer, obj?: GreaterEqualOptions): GreaterEqualOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new GreaterEqualOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static startGreaterEqualOptions(builder: flatbuffers.Builder) {
    builder.startObject(0);
  }

  static endGreaterEqualOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createGreaterEqualOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    GreaterEqualOptions.startGreaterEqualOptions(builder);
    return GreaterEqualOptions.endGreaterEqualOptions(builder);
  }
}
