// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class LogicalNotOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): LogicalNotOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsLogicalNotOptions(bb: flatbuffers.ByteBuffer, obj?: LogicalNotOptions):
      LogicalNotOptions {
    return (obj || new LogicalNotOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsLogicalNotOptions(
      bb: flatbuffers.ByteBuffer, obj?: LogicalNotOptions): LogicalNotOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new LogicalNotOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static startLogicalNotOptions(builder: flatbuffers.Builder) {
    builder.startObject(0);
  }

  static endLogicalNotOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createLogicalNotOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    LogicalNotOptions.startLogicalNotOptions(builder);
    return LogicalNotOptions.endLogicalNotOptions(builder);
  }
}
