// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class MatrixSetDiagOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): MatrixSetDiagOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsMatrixSetDiagOptions(bb: flatbuffers.ByteBuffer, obj?: MatrixSetDiagOptions):
      MatrixSetDiagOptions {
    return (obj || new MatrixSetDiagOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsMatrixSetDiagOptions(
      bb: flatbuffers.ByteBuffer, obj?: MatrixSetDiagOptions): MatrixSetDiagOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new MatrixSetDiagOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static startMatrixSetDiagOptions(builder: flatbuffers.Builder) {
    builder.startObject(0);
  }

  static endMatrixSetDiagOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createMatrixSetDiagOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    MatrixSetDiagOptions.startMatrixSetDiagOptions(builder);
    return MatrixSetDiagOptions.endMatrixSetDiagOptions(builder);
  }
}
