// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class MaximumMinimumOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): MaximumMinimumOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsMaximumMinimumOptions(bb: flatbuffers.ByteBuffer, obj?: MaximumMinimumOptions):
      MaximumMinimumOptions {
    return (obj || new MaximumMinimumOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsMaximumMinimumOptions(
      bb: flatbuffers.ByteBuffer, obj?: MaximumMinimumOptions): MaximumMinimumOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new MaximumMinimumOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static startMaximumMinimumOptions(builder: flatbuffers.Builder) {
    builder.startObject(0);
  }

  static endMaximumMinimumOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createMaximumMinimumOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    MaximumMinimumOptions.startMaximumMinimumOptions(builder);
    return MaximumMinimumOptions.endMaximumMinimumOptions(builder);
  }
}
