// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class PowOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): PowOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsPowOptions(bb: flatbuffers.ByteBuffer, obj?: PowOptions): PowOptions {
    return (obj || new PowOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsPowOptions(bb: flatbuffers.ByteBuffer, obj?: PowOptions): PowOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new PowOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static startPowOptions(builder: flatbuffers.Builder) {
    builder.startObject(0);
  }

  static endPowOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createPowOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    PowOptions.startPowOptions(builder);
    return PowOptions.endPowOptions(builder);
  }
}
