// automatically generated by the FlatBuffers compiler, do not modify

import {CustomQuantization} from '../circle/custom-quantization';


export enum QuantizationDetails {
  NONE = 0,
  CustomQuantization = 1
}

export function unionToQuantizationDetails(
    type: QuantizationDetails,
    accessor: (obj: CustomQuantization) => CustomQuantization | null): CustomQuantization|null {
  switch (QuantizationDetails[type]) {
    case 'NONE':
      return null;
    case 'CustomQuantization':
      return accessor(new CustomQuantization())! as CustomQuantization;
    default:
      return null;
  }
}

export function unionListToQuantizationDetails(
    type: QuantizationDetails,
    accessor: (index: number, obj: CustomQuantization) => CustomQuantization | null,
    index: number): CustomQuantization|null {
  switch (QuantizationDetails[type]) {
    case 'NONE':
      return null;
    case 'CustomQuantization':
      return accessor(index, new CustomQuantization())! as CustomQuantization;
    default:
      return null;
  }
}
