// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class RankOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): RankOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsRankOptions(bb: flatbuffers.ByteBuffer, obj?: RankOptions): RankOptions {
    return (obj || new RankOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsRankOptions(bb: flatbuffers.ByteBuffer, obj?: RankOptions):
      RankOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new RankOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static startRankOptions(builder: flatbuffers.Builder) {
    builder.startObject(0);
  }

  static endRankOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createRankOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    RankOptions.startRankOptions(builder);
    return RankOptions.endRankOptions(builder);
  }
}
