// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class SliceOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): SliceOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsSliceOptions(bb: flatbuffers.ByteBuffer, obj?: SliceOptions): SliceOptions {
    return (obj || new SliceOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsSliceOptions(bb: flatbuffers.ByteBuffer, obj?: SliceOptions):
      SliceOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new SliceOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static startSliceOptions(builder: flatbuffers.Builder) {
    builder.startObject(0);
  }

  static endSliceOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createSliceOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    SliceOptions.startSliceOptions(builder);
    return SliceOptions.endSliceOptions(builder);
  }
}
