// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class SpaceToDepthOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): SpaceToDepthOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsSpaceToDepthOptions(bb: flatbuffers.ByteBuffer, obj?: SpaceToDepthOptions):
      SpaceToDepthOptions {
    return (obj || new SpaceToDepthOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsSpaceToDepthOptions(
      bb: flatbuffers.ByteBuffer, obj?: SpaceToDepthOptions): SpaceToDepthOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new SpaceToDepthOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  blockSize(): number {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
  }

  static startSpaceToDepthOptions(builder: flatbuffers.Builder) {
    builder.startObject(1);
  }

  static addBlockSize(builder: flatbuffers.Builder, blockSize: number) {
    builder.addFieldInt32(0, blockSize, 0);
  }

  static endSpaceToDepthOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createSpaceToDepthOptions(builder: flatbuffers.Builder, blockSize: number):
      flatbuffers.Offset {
    SpaceToDepthOptions.startSpaceToDepthOptions(builder);
    SpaceToDepthOptions.addBlockSize(builder, blockSize);
    return SpaceToDepthOptions.endSpaceToDepthOptions(builder);
  }
}
