/*
 * Copyright (c) 2021 Samsung Electronics Co., Ltd. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// automatically generated by the FlatBuffers compiler, do not modify

import {Int32Vector} from '../circle/int32-vector';
import {Uint16Vector} from '../circle/uint16-vector';
import {Uint8Vector} from '../circle/uint8-vector';


export enum SparseIndexVector {
  NONE = 0,
  Int32Vector = 1,
  Uint16Vector = 2,
  Uint8Vector = 3
}

export function unionToSparseIndexVector(
    type: SparseIndexVector,
    accessor: (obj: Int32Vector|Uint16Vector|Uint8Vector) => Int32Vector | Uint16Vector |
        Uint8Vector | null): Int32Vector|Uint16Vector|Uint8Vector|null {
  switch (SparseIndexVector[type]) {
    case 'NONE':
      return null;
    case 'Int32Vector':
      return accessor(new Int32Vector())! as Int32Vector;
    case 'Uint16Vector':
      return accessor(new Uint16Vector())! as Uint16Vector;
    case 'Uint8Vector':
      return accessor(new Uint8Vector())! as Uint8Vector;
    default:
      return null;
  }
}

export function unionListToSparseIndexVector(
    type: SparseIndexVector,
    accessor: (index: number, obj: Int32Vector|Uint16Vector|Uint8Vector) =>
        Int32Vector | Uint16Vector | Uint8Vector | null,
    index: number): Int32Vector|Uint16Vector|Uint8Vector|null {
  switch (SparseIndexVector[type]) {
    case 'NONE':
      return null;
    case 'Int32Vector':
      return accessor(index, new Int32Vector())! as Int32Vector;
    case 'Uint16Vector':
      return accessor(index, new Uint16Vector())! as Uint16Vector;
    case 'Uint8Vector':
      return accessor(index, new Uint8Vector())! as Uint8Vector;
    default:
      return null;
  }
}
