/*
 * Copyright (c) 2021 Samsung Electronics Co., Ltd. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class SparseToDenseOptions {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): SparseToDenseOptions {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsSparseToDenseOptions(bb: flatbuffers.ByteBuffer, obj?: SparseToDenseOptions):
      SparseToDenseOptions {
    return (obj || new SparseToDenseOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsSparseToDenseOptions(
      bb: flatbuffers.ByteBuffer, obj?: SparseToDenseOptions): SparseToDenseOptions {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new SparseToDenseOptions())
        .__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  validateIndices(): boolean {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
  }

  static startSparseToDenseOptions(builder: flatbuffers.Builder) {
    builder.startObject(1);
  }

  static addValidateIndices(builder: flatbuffers.Builder, validateIndices: boolean) {
    builder.addFieldInt8(0, +validateIndices, +false);
  }

  static endSparseToDenseOptions(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createSparseToDenseOptions(builder: flatbuffers.Builder, validateIndices: boolean):
      flatbuffers.Offset {
    SparseToDenseOptions.startSparseToDenseOptions(builder);
    SparseToDenseOptions.addValidateIndices(builder, validateIndices);
    return SparseToDenseOptions.endSparseToDenseOptions(builder);
  }
}
