name: License Verification

on:
  pull_request:
    branches: [ main ]
    paths: [ 'package.json' ]

jobs:
  license_verification:
    if: ${{ ! contains(github.event.pull_request.labels.*.name, 'PR/NO TEST') }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npx license-checker --unknown --json --out license_list.json
      - shell: bash
        run: npx ts-node infra/license/license-checker.ts license_list.json ${{ matrix.os }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}.json
          path: ${{ matrix.os }}.json
          retention-days: 1

  report_verification_result:
    runs-on: ubuntu-latest

    needs: [ license_verification ]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest.json

      - uses: actions/download-artifact@v3
        with:
          name: macos-latest.json

      - uses: actions/download-artifact@v3
        with:
          name: windows-latest.json

      - run: npm install
      - run: npx ts-node infra/license/check-result-formatter.ts ubuntu-latest.json windows-latest.json macos-latest.json

      - if: ${{ hashFiles('license_check_result.fail') }}
        run: |
          cat license_check_result.md
          exit 1
